repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff-formatter
      - id: ruff
  # REF: https://docs.astral.sh/uv/guides/integration/pre-commit/
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.17
    hooks:
      - id: uv-lock
