name: Run Full Suite of Checks and Tests

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    name: Run unit tests with version ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        py:
          # - "3.15"
          - "3.14"
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          fetch-depth: 0

      - name: Setup python for test - ${{ matrix.py }}
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548  # v6.1.0
        with:
          python-version: ${{ matrix.py }}
      
      # - name: Setup ffmpeg for unit tests (moviepy)
      #   uses: federicocarboni/setup-ffmpeg@37062fbf7149fc5578d6c57e08aed62458b375d6  # v3.1

      - name: Install tox
        run: python -m pip install tox-gh>=1.6

      - name: Setup test suite
        run: tox -vv --notest -e test

      - name: Run test suite
        run: tox --skip-pkg-install -e test
